### ISSUE TITLE
How do I get TEK from a locally recorded zip files with -dl?

### ISSUE THREAD

**Issue by kvaluation** [rocaz/probeCOCOATek#2]
Thanks for the easy-to-use program.
使いやすいプログラムをありがとうございます。

How do I get TEK from a locally recorded zip files with -dl?
-dlオプションでダウンロードしたzipファイルを、どうすればTEKにできるでしょうか？

ERROR message
>probeCOCOATek -z 771.zip                
Error happens, when getting TEK ZIP detail.
Invalid URL '771.zip': No schema supplied. Perhaps you meant http://771.zip?

>probeCOCOATek -z file:///Users/xxxx/771.zip
Error happens, when getting TEK ZIP detail.
No connection adapters were found for 'file:///Users/xxxx/771.zip'

https://twitter.com/info_kvaluation

**Comment by rocaz** [comment]
現在開発中のバージョンでローカルファイルのZIPも読み込み可能にしていますので、しばらくお待ちください。

**Comment by kvaluation** [comment]
ありがとうございます。

**Comment by rocaz** [comment]
Supported with PR #3
