### ISSUE TITLE
Support Python 3.6

### ISSUE THREAD

**Issue by nakayoshix** [rocaz/probeCOCOATek#4]
probeCOCOATekの現在のパッケージ設定情報(setup.cfg)では、Pythonのバージョン制限としてPython 3.7以上となっているようで、例えばWSL上に入れたUbuntu-18.04でpip (pipenv) コマンドでパッケージを入れようとしても、Ubuntuのパッケージで入っている標準Python3のバージョンが3.6.9なので、対応するパッケージのバージョンがないということで以下のようなエラーが出てインストールできません。現状ではGoogle ColaboratyのPython3環境においても同様です。

![](https://user-images.githubusercontent.com/70631/93660730-d4285580-fa8c-11ea-80cb-607ca0f5f08e.png)

一方で、自分でgit clone してきたprobeCOCOATekを直接起動した場合は、以下のようにPython 3.6.9でも問題なく動作することが確認できており、もし特に3.7以上でしか使えない機能を使っているのでなければ、Python 3.6もサポート対象バージョンに加えて頂けると助かります。よろしくお願いいたします。

![](https://user-images.githubusercontent.com/70631/93660869-33d33080-fa8e-11ea-971f-cb1b7f88a8d7.png)

**Comment by rocaz** [comment]
Close #5
