### ISSUE TITLE
Readme.md link miss

### ISSUE THREAD

**Issue by Chamiu** [rocaz/probeCOCOATek#6]
README.mdの「Librahack Incident (Japanese)」のlink URLが、
https://ja.wikipedia.org/wiki/岡崎市立中央図書館事件,
になっているが、末尾に","があるために「ウィキペディアには現在この名前の項目はありません。」ページに飛ばされてしまう。
よって、次のいずれかに修正すると良い。
- 明示 : https://ja.wikipedia.org/wiki/岡崎市立中央図書館事件
- ページID : https://ja.wikipedia.org/?curid=2187212

**Comment by rocaz** [comment]
本来不要なカンマでしたので削除しました。ありがとうございました。
